server:
 port: 6688
 session-timeout: 3600
 uri-encoding: UTF-8
 context-path: /

design:
# 第一个数据库
  demospringbootuser:
   jdbc:
    url: jdbc:mysql://127.0.0.1:3306/demospringbootuser?characterEncoding=utf8&allowMultiQueries=true
    driver: com.mysql.jdbc.Driver
    username: root
    password: root
# 第二个数据库
  demospringbootrole:
   jdbc:
    url: jdbc:mysql://127.0.0.1:3306/demospringbootrole?characterEncoding=utf8&allowMultiQueries=true
    driver: com.mysql.jdbc.Driver
    username: root
    password: root

spring: datasource:initialize:false

#session store type是用来存放session的存储方式，目前Spring boot中只支持Redis方式。
#由于本应用暂无需将session放入redis的需求，故这里就可以将session store type设置为none
#如果使用redis存储session:application.properties配置 spring.session.store-type=redis
#http://www.cnblogs.com/arthy/p/6902960.html
#http://www.cnblogs.com/Impulse/archive/2012/02/03/2337479.html
spring.session.store-type: none
